Repository 2324-4bhif-syp/2324-4bhif-syp-project-franklyn, pull requests merged in 2024-01, with the labels that each got.

#13 [Recorder] feat: add ip-cache
  recorder/src/main/java/at/htl/franklyn/boundary/SavesResource.java
  recorder/src/main/java/at/htl/franklyn/control/ExamineeCacheBean.java
  recorder/src/main/java/at/htl/franklyn/control/ExamineeCacheRepository.java
  recorder/src/main/java/at/htl/franklyn/entity/Examinee.java
  recorder/src/main/java/at/htl/franklyn/services/PingService.java
  recorder/src/main/resources/application.properties
Labels: bug, enhancement

#14 [CI/CD] Upload build artifacts and deploy frontend + server
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/deploy-to-oravm.yaml
  cicd/build-instructor-client.sh
  cicd/build-openbox.sh
  cicd/build-recorder.sh
  cicd/build-server.sh
  cicd/build.sh
  cicd/prod-patch-instructor-client.sh
  cicd/prod-patch-openbox.sh
  cicd/prod-patch-recorder.sh
  cicd/setup-ssh.sh
  instructor-client/env/environment.ts
  openbox/src/main/docker/Dockerfile.jvm
  openbox/src/main/docker/Dockerfile.legacy-jar
  openbox/src/main/docker/Dockerfile.native
  openbox/src/main/docker/Dockerfile.native-micro
  openbox/src/main/resources/application.properties
  recorder/src/main/docker/Dockerfile.jvm
  recorder/src/main/docker/Dockerfile.legacy-jar
  recorder/src/main/docker/Dockerfile.native
  recorder/src/main/docker/Dockerfile.native-micro
  server/server-start.sh
  server/src/main/docker/Dockerfile.jvm
  server/src/main/docker/Dockerfile.legacy-jar
  server/src/main/docker/Dockerfile.native
  server/src/main/docker/Dockerfile.native-micro
  server/src/main/resources/application.properties
Labels: enhancement

#15 Feat/instructor frontend film
  instructor-client/angular.json
  instructor-client/env/environment.ts
  instructor-client/src/app/app.component.html
  instructor-client/src/app/app.component.ts
  instructor-client/src/app/app.routes.ts
  instructor-client/src/app/component/download-examinee/download-examinee.component.css
  instructor-client/src/app/component/download-examinee/download-examinee.component.html
  instructor-client/src/app/component/download-examinee/download-examinee.component.spec.ts
  instructor-client/src/app/component/download-examinee/download-examinee.component.ts
  instructor-client/src/app/component/examinee-download-list/examinee-download-list.component.css
  instructor-client/src/app/component/examinee-download-list/examinee-download-list.component.html
  instructor-client/src/app/component/examinee-download-list/examinee-download-list.component.spec.ts
  instructor-client/src/app/component/examinee-download-list/examinee-download-list.component.ts
  instructor-client/src/app/component/examinee-video/examinee-video.component.css
  instructor-client/src/app/component/examinee-video/examinee-video.component.html
  instructor-client/src/app/component/examinee-video/examinee-video.component.spec.ts
  instructor-client/src/app/component/examinee-video/examinee-video.component.ts
  instructor-client/src/app/component/examinee/examinee.component.ts
  instructor-client/src/app/component/router-components/patrol-mode/patrol-mode.component.css
  instructor-client/src/app/component/router-components/patrol-mode/patrol-mode.component.html
  instructor-client/src/app/component/router-components/patrol-mode/patrol-mode.component.spec.ts
  instructor-client/src/app/component/router-components/patrol-mode/patrol-mode.component.ts
  instructor-client/src/app/component/router-components/video-viewer/video-viewer.component.css
  instructor-client/src/app/component/router-components/video-viewer/video-viewer.component.html
  instructor-client/src/app/component/router-components/video-viewer/video-viewer.component.spec.ts
  instructor-client/src/app/component/router-components/video-viewer/video-viewer.component.ts
  instructor-client/src/app/shared/repository/examinee-data.service.ts
  recorder/src/main/resources/application.properties
Labels: enhancement

#17 fix: frontend active route bug
  instructor-client/src/app/app.component.ts
  instructor-client/src/app/component/examinee-video/examinee-video.component.ts
  instructor-client/src/app/component/router-components/video-viewer/video-viewer.component.ts
Labels: bug
